import sql from 'mssql';

const quoted = (identifier) => identifier.split('.').map((part) => `[${part}]`).join('.');

export class DefectModeStagingRepository {
  constructor(config) { this.config = config; this.pool = undefined; this.tableReady = undefined; }
  async getPool() { if (!this.pool) this.pool = await new sql.ConnectionPool({ server: this.config.server, database: this.config.database, user: this.config.user, password: this.config.password, requestTimeout: this.config.requestTimeout, options: { encrypt: true, trustServerCertificate: this.config.trustServerCertificate } }).connect(); return this.pool; }
  async ensureTable() { this.tableReady ||= (async () => { await (await this.getPool()).request().query(`IF OBJECT_ID(N'${this.config.table}',N'U') IS NULL CREATE TABLE ${quoted(this.config.table)} (Dataset nvarchar(10) NOT NULL, Mode nvarchar(300) NOT NULL, Description nvarchar(4000) NULL, RefreshedAt datetime2 NOT NULL CONSTRAINT DF_DashboardYieldDefectMode_RefreshedAt DEFAULT SYSUTCDATETIME(), CONSTRAINT PK_DashboardYieldDefectMode PRIMARY KEY (Dataset,Mode));`); })(); return this.tableReady; }
  async getModes(dataset) { await this.ensureTable(); const request = (await this.getPool()).request(); request.input('dataset', sql.NVarChar(10), dataset); const result = await request.query(`SELECT Mode AS mode, Description AS description, MAX(RefreshedAt) OVER () AS refreshedAt FROM ${quoted(this.config.table)} WHERE Dataset=@dataset ORDER BY Mode`); return result.recordset.map((row) => ({ ...row, description: row.description || '' })); }
  async replaceModes(dataset, modes) { await this.ensureTable(); const pool = await this.getPool(); const transaction = new sql.Transaction(pool); await transaction.begin(); try { const request = new sql.Request(transaction); request.input('dataset', sql.NVarChar(10), dataset); await request.query(`DELETE FROM ${quoted(this.config.table)} WHERE Dataset=@dataset;`); if (modes.length) { const table = new sql.Table(this.config.table); table.create = false; table.columns.add('Dataset', sql.NVarChar(10), { nullable: false }); table.columns.add('Mode', sql.NVarChar(300), { nullable: false }); table.columns.add('Description', sql.NVarChar(4000), { nullable: true }); modes.forEach((row) => table.rows.add(dataset, row.mode, row.description || null)); await new sql.Request(transaction).bulk(table); } await transaction.commit(); } catch (error) { await transaction.rollback(); throw error; } }
  async addModes(dataset, modes) { const existing = new Set((await this.getModes(dataset)).map((row) => row.mode.toUpperCase())); const missing = modes.filter((row) => !existing.has(String(row.mode || '').toUpperCase())); if (missing.length) await this.replaceModes(dataset, [...(await this.getModes(dataset)), ...missing]); return missing.length; }
}
