import sql from 'mssql';

const quoted = (identifier) => identifier.split('.').map((part) => `[${part}]`).join('.');

export class YieldDefectSettingRepository {
  constructor(config) { this.config = config; this.pool = undefined; this.connecting = undefined; }
  async getPool() { if (this.pool) return this.pool; if (!this.connecting) this.connecting = new sql.ConnectionPool({ server: this.config.server, database: this.config.database, user: this.config.user, password: this.config.password, options: { encrypt: true, trustServerCertificate: this.config.trustServerCertificate } }).connect().then((pool) => (this.pool = pool)).finally(() => { this.connecting = undefined; }); return this.connecting; }
  async ensureTable() { await (await this.getPool()).request().query(`IF OBJECT_ID(N'${this.config.table}', N'U') IS NULL CREATE TABLE ${quoted(this.config.table)} (Dataset nvarchar(10) NOT NULL, Mode nvarchar(300) NOT NULL, GroupName nvarchar(100) NOT NULL, IsIncluded bit NOT NULL, UpdatedBy nvarchar(255) NOT NULL, UpdatedAt datetime2 NOT NULL CONSTRAINT DF_DashboardYieldDefectSetting_UpdatedAt DEFAULT SYSUTCDATETIME(), CONSTRAINT PK_DashboardYieldDefectSetting PRIMARY KEY (Dataset, Mode));`); }
  async list() { await this.ensureTable(); const result = await (await this.getPool()).request().query(`SELECT Dataset AS dataset, Mode AS mode, GroupName AS [group], IsIncluded AS included, UpdatedBy AS updatedBy, UpdatedAt AS updatedAt FROM ${quoted(this.config.table)} ORDER BY Dataset, Mode`); return result.recordset.map((row) => ({ ...row, included: Boolean(row.included) })); }
  async upsert(setting) { await this.ensureTable(); const request = (await this.getPool()).request(); request.input('dataset', sql.NVarChar(10), setting.dataset); request.input('mode', sql.NVarChar(300), setting.mode); request.input('group', sql.NVarChar(100), setting.group); request.input('included', sql.Bit, setting.included); request.input('updatedBy', sql.NVarChar(255), setting.updatedBy); await request.query(`SET XACT_ABORT ON; BEGIN TRANSACTION; UPDATE ${quoted(this.config.table)} WITH (UPDLOCK, SERIALIZABLE) SET GroupName = @group, IsIncluded = @included, UpdatedBy = @updatedBy, UpdatedAt = SYSUTCDATETIME() WHERE Dataset = @dataset AND Mode = @mode; IF @@ROWCOUNT = 0 INSERT INTO ${quoted(this.config.table)} (Dataset, Mode, GroupName, IsIncluded, UpdatedBy) VALUES (@dataset, @mode, @group, @included, @updatedBy); COMMIT TRANSACTION;`); }
}
